### ISSUE TITLE
Feedback 23-junho-2022

### ISSUE THREAD

**Issue by orlandosaraivajr** [murilo-ziani/MEUETL#3]
O projeto está avançando. Registro algumas sugestões: 

- Atualizar o README.md que explique como fazer para reproduzir o ambiente de execução.
- Como testar o código e/ou as estruturas internas ? Crie testes ;)
- O projeto está em evolução. Foque em ter um mínimo que funcione, com testes, para avançar e refatorar o código.
- Em https://github.com/murilo-ziani/MEUETL/blob/92e6aab8b4a6dba2e91e4d3ce47ab0cd96e66256/meuETL.py#L18 como foi encontrado esse número ?

**Comment by murilo-ziani** [comment]
Realizei a atualização do Readme, criei testes e organizei melhor o código.
O número havia sido encontrado como número máximo de id's de acordo com o retorno da api, porém fiz a melhoria com o comando sugerido pelo @Ataíde e agora caso mais cervejas forem adicionadas ao conteúdo o projeto irá realizar o consumo delas também.
Fico no aguardo de mais comentários, obrigado pelas sugestões.
